### ISSUE TITLE
`highlightedSnippet()` does not work

### ISSUE THREAD

**Issue by marcreichel** [spatie/laravel-site-search#14]
When rendering the search results and trying to print the `$hit->highlightedSnippet()` nothing gets returned but `$hit->snippet()` does return something (unhighlighted of course).

Am I missing something?

**Comment by carlosmfnt** [comment]
I'm also experiencing this, `highlightedSnippet()` does not return anything, but `snippet()` returns things that shouldn't be visible. When I'm searching something like "empleo", a simple string, it returns code from another part of the website which is completely unrelated, like in this case, where it returns something related to Axios:

![image](https://user-images.githubusercontent.com/56879478/140700847-ea36ab07-8ffb-42c9-90ce-b02a92e6953e.png)

I'm not sure why this is happening, but it seems that sometimes it captures this random code lines, and passes them as the snippet.

**Comment by marcreichel** [comment]
@carlosmfnt I had the same problem as you. I got rid of this by adding `script` to the ignored css selectors in the `site_search. ignore_content_by_css_selector` setting.
It does not explain why this content gets displayed though. Maybe the Meilisearch typo tolerant feature sees "empleo" somewhere in your XSRF token?! 😅
