### ISSUE TITLE
Error exception being thrown after running php artisan view:cache

### ISSUE THREAD

**Issue by abuhurairah-aar** [spatie/laravel-site-search#25]
I've got an error saying **directory does not exist** in this package vendor directory after running **php artisan view:cache**. The log looks like the following:-

`[2022-01-18 14:46:42] local.ERROR: The "/home/sail/example-app/vendor/spatie/laravel-site-search/src/../resources/views" directory does not exist. {"exception":"[object] (Symfony\\Component\\Finder\\Exception\\DirectoryNotFoundException(code: 0): The \"/home/sail/example-app/vendor/spatie/laravel-site-search/src/../resources/views\" directory does not exist. at /home/sail/example-app/vendor/symfony/finder/Finder.php:592)
[stacktrace]
#0 /home/sail/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Console/ViewCacheCommand.php(67): Symfony\\Component\\Finder\\Finder->in()
#1 /home/sail/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Console/ViewCacheCommand.php(36): Illuminate\\Foundation\\Console\\ViewCacheCommand->bladeFilesIn()
#2 /home/sail/example-app/vendor/laravel/framework/src/Illuminate/Collections/Traits/EnumeratesValues.php(242): Illuminate\\Foundation\\Console\\ViewCacheCommand->Illuminate\\Foundation\\Console\\{closure}()
#3 /home/sail/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Console/ViewCacheCommand.php(37): Illuminate\\Support\\Collection->each()
#4 /home/sail/example-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Foundation\\Console\\ViewCacheCommand->handle()
#5 /home/sail/example-app/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#6 /home/sail/example-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#7 /home/sail/example-app/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#8 /home/sail/example-app/vendor/laravel/framework/src/Illuminate/Container/Container.php(653): Illuminate\\Container\\BoundMethod::call()
#9 /home/sail/example-app/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#10 /home/sail/example-app/vendor/symfony/console/Command/Command.php(298): Illuminate\\Console\\Command->execute()
#11 /home/sail/example-app/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#12 /home/sail/example-app/vendor/symfony/console/Application.php(1005): Illuminate\\Console\\Command->run()
#13 /home/sail/example-app/vendor/symfony/console/Application.php(299): Symfony\\Component\\Console\\Application->doRunCommand()
#14 /home/sail/example-app/vendor/symfony/console/Application.php(171): Symfony\\Component\\Console\\Application->doRun()
#15 /home/sail/example-app/vendor/laravel/framework/src/Illuminate/Console/Application.php(94): Symfony\\Component\\Console\\Application->run()
#16 /home/sail/example-app/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#17 /home/sail/example-app/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#18 {main}
"} `

**Comment by freekmurze** [comment]
I don't think it's related to the code of our package. As you can see the resources/views directory is part of the package.

**Comment by abuhurairah-aar** [comment]
Hi Freek, thanks for the feedback. May I know what did you mean by `resources/views directory is part of the package`? because I happen to not see those directories exist in the package folder.

The faster way to replicate this issue is spin up new laravel repository

`composer create-project laravel/laravel example-app
cd example-app

composer require "spatie/laravel-site-search:^1.0.0"
php artisan vendor:publish --tag="site-search-migrations"
php artisan migrate

php artisan view:cache`

**Comment by freekmurze** [comment]
Hi, you're right, I mistakenly thought that we had some views in this package. 

I've corrected the service provider. The problem is solved in latest version of the package.

Thanks for reporting.

**Comment by abuhurairah-aar** [comment]
Glad that helped. Thanks for the fixing and for the really awesome package. 👍
