### ISSUE TITLE
Issues running first crawl

### ISSUE THREAD

**Issue by NVV-WebManager** [spatie/laravel-site-search#27]
I seem to be having some trouble getting my first index crawled.  I've installed meilisearch in an azure cloud deployment.  In my local laravel app, I've required this package and meilisearch-php sdk package.  

I created the index without issue and updated the table row to include `{"meilisearch":{"url":"https:\/\/[SUBDOMAIN INSERTED].azurewebsites.net","apiKey":"[ADMIN KEY INSERTED]"}}` where the two variables are populated with the correct information for my configuration.  I have tested the Admin API key successfully in meilisearch on the web interface.

Initially when I ran `php artisan site-search:crawl` I received an error about casting (an array was expected for array_map but one of the functions was returning an array as contract model).  

Doing some quick work to see if I could temporarily solve the problem with a simple cast, the issues just kept cascading down into other lines of code, leading me to believe that my installed versions were not meeting requirements.  

I had installed the latest version of meilisearch, but I noticed a suggested version much lower.  So I reverted back to meilisearch-php v. 0.17.2 and the casting issues went away.  

However, now the crawl command is still throwing an error, saying that the Authorization header is missing.  I'm at a loss at this point.  I believe I've implemented all as instructed. Do you have any recommendations for me on where things might be going wrong?

UPDATE: 
Poking at this a little further and I can see that this is still due to the meilisearch-php compatibility.  v0.17.2 uses the old authorization header which is deprecated in the docker instance I deployed.  If I edit the meilisearch-php vendor files directly to update the header then the error pushes on to another compatibility issue.  

So I guess what I need to know is for laravel-site-search v.1.2.0, what version of meilisearch-php is required?  Because the requirements spec'd on the documentation site don't give any information on versioning, but there are clearly some compatibility issues that need to be resolved.  Or perhaps you can update to allow compatibility with the newest meilisearch-php release?

**Comment by freekmurze** [comment]
I currently have no time to dedicate on this, but I'd accept a PR that fixes this.

**Comment by RoyVogel** [comment]
Also have a problem with the first crawl.

 array_map(): Argument #2 ($array) must be of type array, MeiliSearch\Contracts\IndexesResults given.
 
  119▕         return array_map(
    120▕             fn (Indexes $index) => $index->getUid(),
  ➜ 121▕             $this->meilisearch->getAllIndexes(),
    122▕         );

Any solution for this?

**Comment by georgecpacheco** [comment]
> Also have a problem with the first crawl.
> 
> array_map(): Argument #2 ($array) must be of type array, MeiliSearch\Contracts\IndexesResults given.
> 
> 119▕ return array_map( 120▕ fn (Indexes $index) => $index->getUid(), ➜ 121▕ $this->meilisearch->getAllIndexes(), 122▕ );
> 
> Any solution for this?

Same issue here!!

**Comment by mikzero** [comment]
I had the same bug, I have not analyzed the problem, but I updated MeiliSearch to version **v.0.27.2** with the docker and relaunching the crawl was successful.

**Comment by RoyVogel** [comment]
To solve this problem just edit the line with` $ this->meilisearch->getAllIndexes()->getResults ()` This should also fix meilisearch-php and meilisearch update to version .28

This solves the error!
Thanxs, mikzero.

**Comment by freekmurze** [comment]
Glad you found a solution.

If there's something the needs to change in the package to make it work with the latest version of Meilisearch, send a PR 👍  Closing for now!
