### ISSUE TITLE
Markdown rendering on docs page

### ISSUE THREAD

**Issue by lupinitylabs** [spatie/laravel-site-search#8]
Hi,

this is not related to this package, as the markdown looks ok in [installation-setup.md](https://github.com/spatie/laravel-site-search/blob/main/docs/installation-setup.md#install-meilisearch), but it does not render as a list on the [docs page](https://spatie.be/docs/laravel-site-search/v1/installation-setup#install-meilisearch).

![grafik](https://user-images.githubusercontent.com/17774818/137656051-21ba14ce-6510-41e6-b51e-9438ee4c278b.png)

**Comment by freekmurze** [comment]
Fixed!
